version: '3.3'

services:
   mysql:
     build:
       context: ./db
     image: mysql
     restart: always
     container_name: mysql
     ports:
       - "3306:3306"
     hostname: mysql
     environment:
       MYSQL_ROOT_PASSWORD: root

   api:
     depends_on:
       - mysql
     build:
       context: ./content-api
     image: content-api
     hostname: api
     container_name: api
     ports:
       - "3001:3001"
     environment:
       MYSQL_HOST: mysql  
     restart: always
     
   web:
     depends_on:
       - api     
     build:
       context: ./content-web
     image: content-web
     hostname: web
     container_name: web
     ports:
       - "3000:80"
     restart: always     
